language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

before_install:
  - sudo apt-get -y install libjson0 libjson0-dev
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

install:
  - pip install -U setuptools cython coveralls

script:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then
        make isort-check
        make flake8
    fi
    python setup.py test

after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then
        travis wait 30 python setup.py test --coverage=true && coveralls
    else echo failed
    fi
