language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - pip install -U setuptools cython coveralls

script:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then
        make isort-check
        make flake8
    fi
    python setup.py test

after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then
        make coverage && coveralls
    fi
